<a href="https://colab.research.google.com/github/huunhat3112006-sketch/TTNT_NguyenHuuNhat/blob/main/BaiTap1/BTTL/BaiTap1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=3
b=5
print(a+b)
print(a-b)
print(a*b)
print(a/b)



8
-2
15
0.6


In [ ]:
value = "Hello World"
print(value[2:4])

ll


In [ ]:
value =" Hello World "
print(f"{value.strip().upper()}")
print(f"{value.strip().lower()}")
print(f"{value.strip().replace('H','J')}")


HELLO WORLD
hello world
Jello World


In [ ]:
a=5
b=3
if a>b:
  print("Hello World")

Hello World


In [ ]:
a=5
b=3
if a == b:
  print("Yes")
else:
  print("No")

No


In [ ]:
a=5
b=3
if a==b:
  print(1)
elif a>b:
  print(2)
else:
  print(3)

2


In [ ]:
a=b=c=d=3
if a==b and c==d:
  print("Hello World!")


Hello World!


In [ ]:
a=b=3
c=5
d=4
if a==b or c==d:
  print("Hello World!")

Hello World!


In [ ]:
a=5
b=3
result = "Yes" if a>b else "No"
print(result)

Yes


In [ ]:
a=3
b=5
print("A") if a>b else print("=")if a==b else print("B")

B


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
arr = a % 2 ==0
b = a[arr]
print(b)


[2 4 6]


In [ ]:
tong =0
for i in range(0,999):
  if i%3==0 or i%5==0:
    tong+=i
print(tong)

232169


In [ ]:
import numpy as np
a = np.array([3,9,1,4])
b=np.array([2,7,4,3,2,8])
min = len(b) if len(a) > len(b) else len(a)
c = a if len(a)>len(b) else b
for i in range(min):
  c[i] = a[i]+b[i]
print(c)

[ 5 16  5  7  2  8]


In [ ]:
import numpy as np
m=int(input("Nhập số dòng m:"))
n=int(input("Nhập số cột n:"))
a = np.random.randint(0,100,size=(m,n))
print(a)
k=int(input("Nhập số dòng k muốn xuất:"))
print(a[k-1,:]

Nhập số dòng m:3
Nhập số cột n:3
[[73 68  6]
 [48 75 19]
 [ 5 85 84]]
Nhập số dòng k muốn xuất:2
[[48 75 19]
 [ 5 85 84]]
